# -*- coding: utf-8 -*-
"""license-detect.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19oUayZt0jHAs0hYYdcIKOREQuOawmj0N
"""
